"""edit nullable is_attending

Revision ID: 931c2e3bb14c
Revises: 
Create Date: 2023-12-07 15:06:29.511384

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '931c2e3bb14c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_user', schema=None) as batch_op:
        batch_op.alter_column('is_attending',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_user', schema=None) as batch_op:
        batch_op.alter_column('is_attending',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)

    # ### end Alembic commands ###
